# Copyright (c) 2025, PT. SIUMANG TEMAN SUKSES and contributors
# For license information, please see license.txt

import frappe
from frappe.model.document import Document


class PayrollAttendanceSummary(Document):
	# begin: auto-generated code
	# This part is auto-generated by Frappe when DocType is saved.
	# Please leave it as is.
	# end: auto-generated code
	pass
